import google.generativeai as genai
import os
from dotenv import load_dotenv

# 1. Load the hidden variables from the .env file
load_dotenv()

# 2. Grab the API key
api_key = os.getenv("GEMINI_API_KEY")

if not api_key:
    raise ValueError("GEMINI_API_KEY is missing. Please check your .env file.")

# 3. Configure Gemini
genai.configure(api_key=api_key)
def generate_clinical_insights(stroke_type: str, confidence: float, patient_data: dict, gradcam_image_path: str) -> str:
    """
    Passes the prediction, patient data, and Grad-CAM image to a multimodal LLM.
    """
    try:
        # Load the multimodal model
        model = genai.GenerativeModel('gemini-2.5-flash')

        # Upload the Grad-CAM heatmap to the LLM
        heatmap_file = genai.upload_file(path=gradcam_image_path)

        # The Medical Prompt (Strictly engineered to prevent hallucinations)
        prompt = f"""
        You are an expert AI Neurologist Assistant. 
        A Deep Learning CNN has analyzed a brain scan for a {patient_data['age']}-year-old {patient_data['gender']} patient.
        
        CNN Prediction: {stroke_type} Stroke
        AI Confidence: {confidence:.2f}%
        
        I have provided the Grad-CAM heatmap generated by the CNN. The highlighted regions indicate where the neural network detected anomalies leading to this prediction.
        
        Based strictly on established medical guidelines for a {stroke_type} stroke, provide a structured clinical summary for the attending doctor. Format your response in HTML (using <ul>, <li>, <strong>) so it can be rendered directly on a dashboard. 
        
        Include:
        1. <strong>Explainable AI Analysis:</strong> Briefly explain how the highlighted areas in a typical Grad-CAM heatmap correlate with {stroke_type} stroke pathology.
        2. <strong>Common Causes:</strong> Top 4 most likely causes for this specific stroke type.
        3. <strong>Immediate Clinical Next Steps:</strong> Standard emergency treatments or secondary diagnostic tests required.
        4. <strong>Disclaimer:</strong> A bold warning stating this is AI-generated and must be verified by a licensed physician.
        """

        # Generate the response using both Text and the Image
        response = model.generate_content([prompt, heatmap_file])
        
        return response.text

    except Exception as e:
        return f"<p>Error generating clinical insights: {str(e)}</p>"