version: '3.8'

services:
  backend:
    build: ./backend
    container_name: neurascan_api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/scans:/app/scans
      - ./backend/reports:/app/reports
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: neurascan_web
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge